= Spring REST Docs API 文档 Demo
作者 <zhangp@gionee.com>
v1.0, 2018-04-24
:toc: left
:toclevels: 3
:toc-title: 目  录
:doctype: book
:icons: font
:operation-curl-request-title: Curl 请求
:operation-httpie-request-title: HTTPie 请求
:operation-http-request-title: Http 请求
:operation-request-parameters-title: 请求参数说明
:operation-request-fields-title: 请求参数说明
:operation-http-response-title: Http 响应
:operation-response-fields-title: Http 响应字段说明
:operation-links-title: 相关链接

[[overview]]
== 1、概要
本文为API说明文档。

API 分两部分，一部分为完全的 RESTFul 风格的 API ，另一部分为普通的 API

API的说明包括：请求方式、请求地址、请求参数说明和响应消息等。

[[overview-response]]
== 2、通用说明

*非 RESTFul API 通用响应消息说明*

|===
| 字段 | 类型 | 解释

| state
| int
| 1为成功，0为失败，其他为自定义状态

| data
| Object
| 请求的数据

| msg
| String
| 响应附带的消息
|===

[[resources-restful]]
== 3、RESTFul API

[[resources-restful-account]]
=== 3.1、Account

[[resources-restful-account-profile]]
==== 3.1.1、Account 接口信息描述

operation::restful-account-profile[snippets='curl-request,httpie-request,http-request,http-response,response-field']

[[resources-restful-account-index]]
==== 3.1.2、Account 根
operation::restful-account-index[snippets='curl-request,httpie-request,http-request,http-response,response-fields,links']

[[resources-restful-account-add]]
==== 3.1.3、Account 添加

operation::restful-account-add[snippets='curl-request,httpie-request,http-request,request-parameters,http-response,response-fields']
[[resources-restful-account-update]]
==== 3.1.4、Account 更新

operation::restful-account-update[snippets='curl-request,httpie-request,http-request,request-parameters,http-response,response-fields']

[[resources-restful-account-get]]
==== 3.1.5、Account 获取

operation::restful-account-get[snippets='curl-request,httpie-request,http-request,http-response,response-fields']
[[resources-general]]